/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eri
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class UAS_PBO_CRUD_1778 extends javax.swing.JFrame {
    private float gaji_2_1778;

    /**
     * Creates new form 
     */
    DefaultTableModel model;
    public UAS_PBO_CRUD_1778() {
        initComponents();
        String [] judul ={"NIM", "NAMA", "TEMPAT LAHIR", "TANGGAL LAHIR", "KODE WALI", "NAMA WALI", "ALAMAT WALI","PEKERJAAN", "GAJI"};
        model = new DefaultTableModel (judul,0);
        tabel_1778.setModel(model);
        tampilkan_1778();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nim_1778 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama_1778 = new javax.swing.JTextField();
        tempat_lhr_1778 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tgl_lhr_1778 = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_1778 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kd_wali_1778 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nm_wali_1778 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        alamat_wali_1778 = new javax.swing.JTextField();
        pekerjaan_1778 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        gaji_1778 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        uang_kuliah_1778 = new javax.swing.JLabel();
        btn_hitung_uang_kuliah = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        uang_kuliah_2_1778 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ENTRI FORM MAHASISWA");

        jLabel2.setText("NIM");

        jLabel3.setText("NAMA");

        jLabel4.setText("TEMPAT LAHIR");

        jLabel5.setText("TANGGAL LAHIR");

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        tabel_1778.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tabel_1778.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_1778MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_1778);

        jLabel6.setText("DATA MAHASISWA");

        jLabel7.setText("DATA WALI");

        jLabel8.setText("KODE WALI");

        jLabel9.setText("NAMA WALI");

        jLabel10.setText("ALAMAT WALI");

        jLabel11.setText("PEKERJAAN");

        jLabel12.setText("GAJI");

        uang_kuliah_1778.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uang_kuliah_1778.setText("Uang Kuliah");

        btn_hitung_uang_kuliah.setText("Hitung Uang Kuliah");
        btn_hitung_uang_kuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitung_uang_kuliahActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("=");

        uang_kuliah_2_1778.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uang_kuliah_2_1778.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_hitung_uang_kuliah)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tempat_lhr_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tgl_lhr_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nama_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nim_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_edit)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addComponent(jLabel8))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(kd_wali_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nm_wali_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alamat_wali_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pekerjaan_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gaji_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uang_kuliah_1778)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uang_kuliah_2_1778, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_hapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_reset)))))
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nim_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nama_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tempat_lhr_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(tgl_lhr_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kd_wali_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nm_wali_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alamat_wali_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(pekerjaan_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(gaji_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uang_kuliah_1778)
                            .addComponent(jLabel13)
                            .addComponent(uang_kuliah_2_1778, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus)
                    .addComponent(btn_reset)
                    .addComponent(btn_hitung_uang_kuliah))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/uas","root","");
            cn.createStatement().executeUpdate("insert into data_1778 values"+"('"+nim_1778.getText()+"','"+nama_1778.getText()+"','"+tempat_lhr_1778.getText()+"','"+tgl_lhr_1778.getText()+"','"+kd_wali_1778.getText()+"','"+nm_wali_1778.getText()+"','"+alamat_wali_1778.getText()+"','"+pekerjaan_1778.getText()+"','"+gaji_1778.getText()+"')");
            
            tampilkan_1778();
            reset();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Isi Semua Datanya!");
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/uas","root","");
            cn.createStatement().executeUpdate("update data_1778 set nim_1778='"+nim_1778.getText()+"',nama_1778 ='"+nama_1778.getText()+"',tempat_lhr_1778 ='"+tempat_lhr_1778.getText()+"',tgl_lhr_1778='"+tgl_lhr_1778.getText()+"',kd_wali_1778='"+kd_wali_1778.getText()+"',nm_wali_1778='"+nm_wali_1778.getText()+"',alamat_wali_1778='"+alamat_wali_1778.getText()+"',pekerjaan_1778='"+pekerjaan_1778.getText()+"',gaji_1778='"+gaji_1778.getText()+"'");
            tampilkan_1778();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabel_1778MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_1778MouseClicked
        int i = tabel_1778.getSelectedRow();
        
        if(i>=i){
            nim_1778.setText(model.getValueAt(i, 0).toString());
            nama_1778.setText(model.getValueAt(i, 1).toString());
            tempat_lhr_1778.setText(model.getValueAt(i, 2).toString());
            tgl_lhr_1778.setText(model.getValueAt(i, 3).toString());
            kd_wali_1778.setText(model.getValueAt(i, 4).toString());
            nm_wali_1778.setText(model.getValueAt(i, 5).toString());
            alamat_wali_1778.setText(model.getValueAt(i, 6).toString());
            pekerjaan_1778.setText(model.getValueAt(i, 7).toString());
            gaji_1778.setText(model.getValueAt(i, 8).toString());
        }
    }//GEN-LAST:event_tabel_1778MouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/uas","root","");
            cn.createStatement().executeUpdate("delete from data_1778 where nim_1778 ='"+nim_1778.getText()+"'");
            tampilkan_1778();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_hitung_uang_kuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitung_uang_kuliahActionPerformed
       
        setGaji_1778(Float.parseFloat(gaji_1778.getText()));
        uang_kuliah_2_1778.setText(Biaya_1778());
        
    }//GEN-LAST:event_btn_hitung_uang_kuliahActionPerformed

    private void reset(){
        nim_1778.setText("");
        nama_1778.setText("");
        tempat_lhr_1778.setText("");
        tgl_lhr_1778.setText("");
        kd_wali_1778.setText("");
        nm_wali_1778.setText("");
        alamat_wali_1778.setText("");
        pekerjaan_1778.setText("");
        gaji_1778.setText("");
        uang_kuliah_2_1778.setText("0");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UAS_PBO_CRUD_1778().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_wali_1778;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hitung_uang_kuliah;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JTextField gaji_1778;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kd_wali_1778;
    private javax.swing.JTextField nama_1778;
    private javax.swing.JTextField nim_1778;
    private javax.swing.JTextField nm_wali_1778;
    private javax.swing.JTextField pekerjaan_1778;
    private javax.swing.JTable tabel_1778;
    private javax.swing.JTextField tempat_lhr_1778;
    private javax.swing.JTextField tgl_lhr_1778;
    private javax.swing.JLabel uang_kuliah_1778;
    private javax.swing.JTextField uang_kuliah_2_1778;
    // End of variables declaration//GEN-END:variables

   
    
   
    private void tampilkan_1778() {
        int row = tabel_1778.getRowCount();
        for (int a = 0; a<row;a++){
            model.removeRow(0);
        }
        
        try {
          Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/uas","root","");
          ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM data_1778");
          while(rs.next()){
              String data []= {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)};
              model.addRow(data);
          }
        } catch (SQLException ex) {
            Logger.getLogger(UAS_PBO_CRUD_1778.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public void setGaji_1778(float gaji_2_1778) {
        
        this.gaji_2_1778 = gaji_2_1778;
    }
    
     public String Biaya_1778(){
        if (gaji_2_1778>4.000000)
            return "7 Juta";
        else if (gaji_2_1778>2.000000)
            return "3 Juta";
        else if (gaji_2_1778>1.000000)
            return "0 juta";
        else
            return "0";
    }
}
    
    

